# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-26 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='last_update',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='posted',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
